<?php

namespace App\Models;
use App\Events\Contact;

class ContactUs extends Model
{
    //
    protected $guarded = [];

    public function afterSave($model)
    {
        event(new Contact( $model ));
        parent::afterSave($model); // TODO: Change the autogenerated stub
    }
}
